name: Question
description: Ask a question
title: "Query: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what
    attributes:
      label: What is your question?
      description: Explain the question bestto your ability?
      placeholder: A description of your question.
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: username@example.com
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/PostGraphDB/postgraph)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true


